### PR TITLE
Fix type checking in config examples

### PR DESCRIPTION
**Pull request by karlhorky**
Hi there, thanks for Rspack and the ecosystem, really cool initiative!

Quick PR to fix the type checking in the configuration file examples you have, similar to [the config page](https://www.rspack.dev/config/index.html#type-checking)

This is because of this underlying problem in TypeScript:

- https://github.com/microsoft/TypeScript/issues/47107

### CODE REVIEW

**Comment by karlhorky** [comment]
Oh I also saw that there were many instances of this same problem in the main `web-infra-dev/rspack` repo:

- https://github.com/search?q=repo%3Aweb-infra-dev%2Frspack%20%2F**%20%40type%20%7Bimport(%27%40rspack%2Fcli%27).Configuration%7D%20*%2F%20const%20config%20%3D%20%7B&type=code

Probably could be another fairly simple PR

**Comment by hardfist** [comment]
it seems typecheck works for module.exports?
image

**Comment by karlhorky** [comment]
> it seems typecheck works for module.exports?

it is indeed confusing (seems like it works at first) - but it is indeed broken, check the behavior here:

- https://github.com/microsoft/TypeScript/issues/47107
- https://github.com/microsoft/TypeScript/issues/51819

**Comment by karlhorky** [comment]
Example here: [TypeScript Playground](https://www.typescriptlang.org/play?filetype=js#code/JYWwDg9gTgLgBADzgMyhEcDkABKBnMAQwGMBrAemIBthMAoO8gKibmxgE8wBTOAb1CRYAChz4iZSjUwBKAHQBhCADtkwAOYBXKIRjAVAXzhNydEBAAmmqtzncEQmHjgBefnThxuymFA4cALndPTxBCYGUgzDlyPChicgiLezkAKzwETAAaDzgDHIMGZlZ2Ll4BcGgYUVwCEgpqWnklVQ1tXX1lIxM6YhU8eD7W9Vdgrx8-QLHQ8MisGLiEpJT0zJzPfLoDAG46IA)

```js
import x from '@rspack/cli'

/** @type {import('@rspack/cli').Configuration} */
module.exports = {
  entryy: { // 💥 no error
    main: './src/index.jsx',
  },
}

/** @type {import('@rspack/cli').Configuration} */
const config = {
  entryy: { // ✅ error: Type '{ entryy: { main: string; }; }' is not assignable to type 'RspackOptions'. Object literal may only specify known properties, but 'entryy' does not exist in type 'RspackOptions'. Did you mean to write 'entry'?
    main: './src/index.jsx',
  },
};
```

Screenshot 2023-04-20 at 09 29 59

**Comment by hardfist** [comment]
that's interesting, then we will change to the right way

**Review by hardfist — APPROVED** [review]

**Review by chenjiahan — APPROVED** [review]

**Comment by karlhorky** [comment]
Great, thanks for the reconsideration, review and merge!

Seems like @danielkoller opened a PR to fix the examples too:

- https://github.com/web-infra-dev/rspack/pull/2965

**Pull request merged**
